Updates based on feedback

diff --git a/scripts/eval-pr b/scripts/eval-pr
--- a/scripts/eval-pr
+++ b/scripts/eval-pr
@@ -5,11 +5,11 @@
 # Copyright (c) 2022 Freeciv21. This file is part of Freeciv21. Freeciv21 is free software: you can
 # redistribute it and/or modify it under the terms of the GNU General Public License as published by the
 # Free Software Foundation, either version 3 of the  License, or (at your option) any later version. You
-# should have received  a copy of the GNU General Public License along with Freeciv21. If not, see
+# should have received a copy of the GNU General Public License along with Freeciv21. If not, see
 # https://www.gnu.org/licenses/.
 #
 # Bash shell script to aid the process of evaluating a pull request
-#--
+#---
 
 version="1.0"
 re='^[0-9]+$'
@@ -20,9 +20,10 @@ fi
 
 help ()
 {
+  echo ""
   echo "Freeciv21: Evaluate a Pull Request as documented at"
   echo "  https://longturn.readthedocs.io/en/latest/Contributing/eval-pull-request.html"
-  echo "Version: $version"
+  echo "$0 Version: $version"
   echo ""
   echo "Should be executed from the root of the Freeciv21 source directory."
   echo ""
@@ -37,20 +38,26 @@ help ()
 
 base_setup ()
 {
+  # Ensure we are on the master branch before starting.
   local branch=$(git rev-parse --abbrev-ref HEAD)
   if ! [[ "$branch" == "master" ]]; then
-    echo "-- Stashing changes and checking out master branch."
-    echo ""
-    git stash
-    git checkout master
-    echo ""
+    echo "-- Error: Ensure you have stashed all work and have checked out the master branch before starting."
+    echo "-- You are on branch: $branch. If this is a testing/pr_# branch, run a cleanup operation first or"
+    echo "-- manually stash work and checkout master to evaluate another pull request."
+    exit 255
   fi
 
-  echo "-- Fetching upstream master"
-  echo ""
-  git fetch upstream master
+  # Ensure we are in the root of the freeciv21 source tree before starting.
+  if ! [[ -e CMakePresets.json ]]; then
+    echo "-- Error: Ensure you are at the root of the Freeciv21 source tree before starting."
+    exit 255
+  fi
 
+  echo "-- Fetching upstream"
   echo ""
+  git fetch upstream || exit 255
+
+
   echo "-- Creating a testing branch for PR $pull_request."
   echo ""
   git checkout -b testing/pr_$pull_request upstream/master
@@ -60,12 +67,15 @@ base_setup ()
   echo ""
   wget https://github.com/longturn/freeciv21/pull/$pull_request.diff -O pr$pull_request.diff
 
-  echo ""
   echo "-- Applying the .diff via patch."
   echo ""
   patch -p1 < pr$pull_request.diff
   rm pr$pull_request.diff
-  rm -Rf build
+
+  # Always start with a empty build directory when testing
+  if [[ -e build_$pull_request ]]; then
+    rm -Rf build_$pull_request
+  fi
 }
 
 start ()
@@ -79,10 +89,16 @@ start ()
   echo ""
   echo "-- Building."
   echo ""
-  cmake -S . -B build -G Ninja -DCMAKE_INSTALL_PREFIX=$PWD/build/install -DCMAKE_BUILD_TYPE=Debug
-  cmake --build build
-  cmake --build build --target install
-  cmake --build build --target package
+  # We ask for a debug build in order to run the code through a debugger while evaluating
+  cmake -S . -B build_$pull_request -G Ninja -DCMAKE_INSTALL_PREFIX=$PWD/build/install -DCMAKE_BUILD_TYPE=Debug
+  cmake --build build_$pull_request
+  # Always test the installer
+  cmake --build build_$pull_request --target install
+
+  # Only run on Debian based linux or MSYS2
+  if which dpkg &>/dev/null || [[ $MSYSTEM ]]; then
+    cmake --build build_$pull_request --target package
+  fi
 
   echo ""
   echo "-- PR $pull_request is ready to be evaluated. Run $0 -c $pull_request to cleanup."
@@ -93,27 +109,30 @@ autogame ()
 {
   echo ""
   echo "Starting an ASAN autogame Eval Process for PR# $pull_request"
+  echo ""
+
+  if [[ $MSYSTEM ]]; then
+    echo "-- Error: ASan not supported on MSYS2."
+    exit 255
+  fi
 
   base_setup
 
   echo ""
   echo "-- Building."
   echo ""
-  mkdir build
-  for dir in build
-  do
-    (
-    cd build || exit 255
+  if ! [[ -e build_$pull_request ]]; then
+    mkdir build_$pull_request
+    cd build_$pull_request
     cmake --preset ASan -S ..
     cd ..
-    )
-  done
-  cmake --build build
+  fi
+  cmake --build build_$pull_request
 
-  echo ""
   echo "-- Running Autogame on port 5556."
   echo "-- If you want to observe the game, open another shell and run this command to open a client"
   echo "     ./build/freeciv21-client -a -p 5556 -s localhost"
+  echo ""
   export ASAN_OPTIONS="halt_on_error=0"
   ./build/freeciv21-server -r ./data/test-autogame.serv
 
@@ -131,7 +150,7 @@ cleanup ()
   local branch=$(git rev-parse --abbrev-ref HEAD)
   if ! [[ "$branch" == "testing/pr_$pull_request" ]]; then
     echo "Error: Attempting cleanup on incorrect pull request number."
-    echo "The current eval is on branch: $branch"
+    echo "The current branch is: $branch" and pull request: $pull_request
     echo ""
     exit 255
   fi
@@ -148,6 +167,10 @@ cleanup ()
 
   if [[ "$ASAN_OPTIONS" ]]; then
     export ASAN_OPTIONS=
+  fi
+
+  if [[ -e build_$pull_request ]]; then
+    rm -Rf build_$pull_request
   fi
 
   echo ""
